### ISSUE TITLE
Git tags are not fetched.

### ISSUE THREAD

**Issue by mook-as** [telia-oss/github-pr-resource#136]
Hi!

For some of our pipelines, we want to build artifacts with embedded version numbers, normally supplied via git tags.  Ideally the GitHub PR resource would fetch enough tags such that `git describe` would do the normal thing and report things based on tags.

However, it looks like the git checkout produced from the `in` step does not contain any tags.  Doing a similar `git init` / `git pull <base>` / `git fetch pulls/<n>/head` has the same behaviour.  Reading a random [stack overflow answer](https://stackoverflow.com/questions/41813643/), though, it looks like this is because the pull & fetch commands do not specify any local refs.

I think all that's needed is to change [GitClient.Pull#80] to do a `{"pull", endpoint + ".git", fmt.Sprintf("%s:%s", branch, branch)}` instead of `{"pull", endpoint + ".git", branch}`; that should pull in tags that are ancestors of the base branch.  Alternatively, do something similar for [GitClient.Fetch#114] too; but currently we have no local refs for that (though `pull/nnn/head` is a perfectly fine local branch name too).

Please let me know if any of this sounds reasonable, thanks!

[GitClient.Pull#80]: https://github.com/telia-oss/github-pr-resource/blob/94d3f6b12b017a29b2a0aa1f1375d59a6a87c1eb/git.go#L80
[GitClient.Fetch#114]: https://github.com/telia-oss/github-pr-resource/blob/94d3f6b12b017a29b2a0aa1f1375d59a6a87c1eb/git.go#L114

**Comment by itsdalmo** [comment]
Hi! This to me sounds like a job for the [git-resource](https://github.com/concourse/git-resource) and not `github-pr-resource`. Have you had a look at using that one instead?

**Comment by mook-as** [comment]
Hi! Yes, this works with the `git-resource`, but that main point of using the `github-pr-resource` is to check my PRs (which involved running the build steps to make sure we didn't break that, and to dump the artifacts somewhere if necessary for testing before merging the PRs).

As far as I can tell from the docs, it's not possible for me to take the git ref from `github-pr-resource` and cause `git-resource` to pull that commit; example pipeline snippets (or pointers to other pipelines) if that could be done would be very helpful.

**Comment by itsdalmo** [comment]
From your description, I'm still not sure why you need tags in the git history 😅 

> As far as I can tell from the docs, it's not possible for me to take the git ref from github-pr-resource and cause git-resource to pull that commit;

`get` just uses regular git commands in this resource, so you could just use the `git-resource` and then have a task which does `git fetch --all` and then checkout the commit from the PR (you can find the commit SHA in `.git/resource/medata.json` and in `.git/resource/head_sha`)?

**Comment by pf-qiu** [comment]
We are encountering the same problem when we try to migrate from `jtarchie/pr`.
On our CI system we automatically generate a piece of code that contains the current "version". It gets the version string via `git describe` and thus tags are needed.
`jtarchie/pr` gets the tags because it uses `git clone` directly instead of `git pull` I suppose.
Adding a separate task requires update to the entire pipeline. If you have a lot of jobs then that would be painful. In addition the `git fetch --all` approach doesn't work well if the repo is private. Need to pass in a deploy key or the token.

**Comment by gabistoenescu** [comment]
This is quite a limitation indeed.
As exemplified in the previous comment there is a real need for tags when a CI task needs to build snapshot-like artifacts using a build tool supporting automatic "_semver_" generation.
I am hoping the PR resource will be enhanced soon  to include the tags.

In the meantime, for what is worth, here's a brief description of our temporary hack to overcome this issue. Prepend the following functionality to the Concourse task that consumes the PR resource and needs the tags:
1. Configure the git remote
The PR resource doesn't do much git configuration and you'll need the remotes (which are missing) in order to talk to your source git repo. Executing something like this will do:
```
    url="https://${GITHUB_USER}:${GITHUB_TOKEN}@${GITHUB_PROJECT}.git"
    git remote add origin $url
```
Of course you can configure the git remote with whatever protocol and access scheme that works for your particular setup.

2. Fetch the tags
` git fetch --tags --force`

**Comment by creatyvtype** [comment]
+1 Need this for monorepo using lerna to publish beta versions. Lerna in CI cannot determine which packages are affected because git tags are not present, so it just publishes everything.

**Comment by jhosteny** [comment]
I added a formal PR that addressed this with a configuration option and the fix posted by @jandubois
