### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by fhuitelec** [telia-oss/github-pr-resource#160]
Hi! 👋

Thank you for your amazing work!

I'd like to use the work done in https://github.com/telia-oss/github-pr-resource/pull/132 which brings a new `labels` filter merged on August, 17 on `master` but your last release (and, thus, docker image) was created 8 days earlier.

Would it be possible to release a new version from `master`? (or any other stable reference you use in your release cycle that would embark #132 for that matter)

FYI, I'm not blocked since I have, temporarily, re-built my own image from `master`.

— Thank you!

**Comment by itsdalmo** [comment]
Hi @fhuitelec and thanks for raising this issue; I've been reluctant to make a new release until I've had a chance to investigate #156 since I noticed that the cost of `check` has increased. Unfortunately I have not had a chance to look at it yet (vacation and otherwise tied up), and I'm a bit reluctant to wing it since resources tend to be specified with an implied `version: "latest"` 😅

**Comment by frshwtr** [comment]
Hi @itsdalmo. Any updates on #156? I would also like to consume the `labels` filter for a pipeline.

Thanks! :)

**Comment by itsdalmo** [comment]
I've just made a `v0.19.0` release and the `latest` tag on Dockerhub has already [been updated](https://hub.docker.com/repository/docker/teliaoss/github-pr-resource/tags?page=1). Thank you for your patience folks 🙌

**Comment by fhuitelec** [comment]
Thank you @itsdalmo!
