### ISSUE TITLE
Update multiple statuses

### ISSUE THREAD

**Issue by dnd** [telia-oss/github-pr-resource#170]
Is there any possibility at present, or has it been considered to allow pushing multiple status updates at a time(maybe through a status file)? 

Because of the way concourse works to try and be somewhat more efficient in my job processing, and resource usage, I am stacking multiple checks inside of the same task. This means that when I finish, I only have one success/failure hook that I can use to push a status. I'm currently working around this by using the `description_file` to indicate which of the checks failed, but it would be nice to be able to report them as first class checks.

**Comment by RNag** [comment]
I think this is an interesting situation @dnd  - sorry but it took me a while to actually process what the question was asking 😅 

I was wondering if i can offer an alternative (not sure if it would work well for you). Currently we have a couple optional checks, such as minimum test coverage and minimum code linting / style checking rating - this is only a suggestion based on our team's standards though. Our solution is to use `comment_file` as well as `delete_previous_comments` to provide insight in the PR page on what checks passed or failed.

So a typical comment posted by our CI build might look something like this:
```
✅ Tests passed
> A brief summary

❌ Something else failed
> Details on the failure
```

I was just curious if this is something that you've already tried before? There might be a good reason to require multiple status checks as well, that I'm probably not aware of as well.

**Comment by itsdalmo** [comment]
Hi @dnd and thanks for the issue! If I understood your question correctly, I think another solution (besides the one mentioned by @RNag) is to simply have multiple `put` steps in your `on_failure` and `on_success`, one per status you would like to update?

**Comment by dnd** [comment]
@RNag @itsdalmo sorry for the delay. Thanks for the responses. 

The `comment_file` was something I thought of as well, but it makes it hard to see at a glance what went wrong when the PR ends up with a lot of conversation.

For using multiple steps in `on_failure` and `on_success`, since only one of the internal checks has to fail, and then it triggers the failure block, how would I be able to report that some of those checks are successful, and some aren't?

**Comment by RNag** [comment]
I guess i would personally try to make do with one of 1) `comment_file` - even if you have a high volume of comments, you would basically just need to grab the last one 2) maybe some kind of external notification, such as send to email or slack so you can easily be notified of any failures or issues.

If you do need multiple statuses (which I guess now that I think about it, could be useful for configuring branch protection rules as well, so mergeability for example can only be performed after X number of statuses pass), I guess i would suggest to see if you can make some changes to the pr-resource and modify it so that it pushes various statuses from a `status_file`. If for some reason you are unable to, i could possibly look into adding this feature as well.

**Comment by itsdalmo** [comment]
>For using multiple steps in on_failure and on_success, since only one of the internal checks has to fail, and then it triggers the failure block, how would I be able to report that some of those checks are successful, and some aren't?

Based on the above, it sounds like your checks should perhaps be implemented as individual jobs and set a unique `context` on `put` for each of the jobs. This also gives you the added benefit of running your checks in parallel.

I will close the issue now because it has gone stale, and also because I believe the above is the most "correct" way to solve your problem (as I understand it). That being said, feel free to re-open if you don't agree 😅
