### ISSUE TITLE
Feature request: Autoregister webhooks

### ISSUE THREAD

**Issue by keymon** [telia-oss/github-pr-resource#60]
Just to write down a nice feature idea: To make this resource autoregister the webhook in the github repository. 

This can be configured by adding a `register_webhook: true` in the params, and doing the registration either in the `get` or by using a explicit `put` operation.

That would speed up the process of configuring new pipelines, even completely automate it

**Comment by itsdalmo** [comment]
Agreed, this would make the setup a lot easier and generally be a useful feature 👍 
This would require two things from the user:

- The `webhook_token` would have to be passed to the source configuration.
- The access token needs to include `POST /repos/:owner/:repo/hooks` permissions to [create a webhook](https://developer.github.com/v3/repos/hooks/#create-a-hook).

With that information we could probably construct the URL for the webhook from the [metadata](https://concourse-ci.org/implementing-resources.html) which is passed to tasks. However, I think it would make more sense if this was a separate resource in order to manage the lifecycle of the webhook, but then the metadata passed to the task would not be correct 🤔

**Comment by keymon** [comment]
It does not need to be a separated resource. 

You can set a custom option in the  `put`, so you can add a simple task to configure the endpoint as needed, something like:

```
 - name: add-web-hook
  plan:
  - put: pull-request
    params:
      register_webhook: true
```

**Comment by itsdalmo** [comment]
Sorry for the late response here! The premise here is that if we create a webhook, we also need to be able to delete it when it is no longer needed. But since this resource does not track webhooks it creates (and never will), we can't track the ID of the webhook (returned on create) which is needed to delete it when someone sets `register_webhook: false` again.

In following, to delete a webhook we created we'd need to [ListHooks](https://godoc.org/github.com/google/go-github/github#RepositoriesService.ListHooks), then match the [Hook.URL](https://godoc.org/github.com/google/go-github/github#Hook) against the current URL, then grab the ID and delete the Hook. This has the following problems:
- We'll create a new hook and leave an unused hook everytime the resource (or pipeline) changes names.
- Since we can't know whether the flag was set to `true` in the past (we have no state), we'd have to list webhooks on every invocation of `put` to see if there are any webhooks that need to be deleted. Which means the resource would use 1 more API call for per `put`  (or `get`, any step where metadata is available) for anyone who used the resource, irrespective of whether they had ever used it to create a webhook.
- All `put` or `get` steps (where concourse metadata is available) would incur an extra API calls on every invocation, irrespective of what the `register_webhook` flag was currently set to, since we'd have no way of knowing whether it had been set to `true` in the past.
- (We could work around the above by using an enumeration of some sort, but that feels very hacky).

As useful as it would be to auto-register webhooks, I don't think its something that can be done in a good way currently - but perhaps its possible that this changes when Resources V2 land.

**Comment by itsdalmo** [comment]
I'll close this issue. It would be a great feature to have, but I just don't see it being viable in a good way.
