### ISSUE TITLE
Option to ignore missing comment_file

### ISSUE THREAD

**Issue by DSpeichert** [telia-oss/github-pr-resource#75]
We try to get output of a failed task in `comment_file` but sometimes the task fails such that no file is generated. We would like the option to ignore that and simply register the desired status.

**Comment by itsdalmo** [comment]
Hi and thanks for the issue! I think if we implemented this we'd be silently ignoring errors when someone specifies the wrong path to a file. Since `comment_file` will only create a comment if the file is not empty, is it not possible for you to just `touch` the file before writing to it - iff nothing is written, no comment will be created?

**Comment by itsdalmo** [comment]
Closing this due to lack of comments.
